// ExternalObjectsControlCom.idl : IDL source for ExternalObjectsControlCom
//

// This file will be processed by the MIDL tool to
// produce the type library (ExternalObjectsControlCom.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";


enum EVT
{
    crtDyno = 0
	, delDyno
	, crtPed
	, delPed
	, evtUndefined
};


[
	object,
	uuid(180764CB-8BB2-47A2-92E3-B59AAA7A36B0),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IDistriObjsCtrl : IDispatch{
	[id(1)] HRESULT CreateNetworkExternalObjectControl([in] LONG imple, [in] LONG terminal);
	[id(2)] HRESULT ReleaseNetworkExternalObjectControl(void);
	[id(3)] HRESULT Initialize([in] BSTR pathScene);
	[id(4)] HRESULT UnInitialize(void);
	[id(5)] HRESULT QFrontEvent([out]enum EVT* evt, [out] VARIANT_BOOL* empty);
	[id(6)] HRESULT QPopEvent();
	[id(7)] HRESULT GetcrtDynoTuple([out] LONG* id_local, [out] BSTR* name, [out] LONG* solId
									, [out] DOUBLE* xSize, [out] DOUBLE* ySize, [out] DOUBLE* zSize
									, [out] DOUBLE* xPos, [out] DOUBLE* yPos, [out] DOUBLE* zPos
									, [out] DOUBLE* xTan, [out] DOUBLE* yTan, [out] DOUBLE* zTan
									, [out] DOUBLE* xLat, [out] DOUBLE* yLat, [out] DOUBLE* zLat);
	[id(8)] HRESULT GetdelDynoTuple([out] LONG* id_local);
	[id(9)] HRESULT GetcrtPedTuple([out] LONG* id_local, [out] BSTR* name, [out] LONG* solId
									, [out] DOUBLE* xSize, [out] DOUBLE* ySize, [out] DOUBLE* zSize
									, [out] DOUBLE* xPos, [out] DOUBLE* yPos, [out] DOUBLE* zPos
									, [out] DOUBLE* xTan, [out] DOUBLE* yTan, [out] DOUBLE* zTan
									, [out] DOUBLE* xLat, [out] DOUBLE* yLat, [out] DOUBLE* zLat);
	[id(10)] HRESULT GetdelPedTuple([out] LONG* id_local);
	[id(11)] HRESULT PreUpdateDynamicModels(void);
	[id(12)] HRESULT PostUpdateDynamicModels(void);
	[id(13)] HRESULT OnGetUpdate([in] LONG id_local, [out] VARIANT_BOOL* received
							, [out] DOUBLE* xPos, [out] DOUBLE* yPos, [out] DOUBLE* zPos
							, [out] DOUBLE* xTan, [out] DOUBLE* yTan, [out] DOUBLE* zTan
							, [out] DOUBLE* xLat, [out] DOUBLE* yLat, [out] DOUBLE* zLat);
};
[
	uuid(32C477E7-84FC-4F7A-96B9-4F86FA80DEE5),
	version(1.0),
]
library ExternalObjectsControlComLib
{
	importlib("stdole2.tlb");
	[
		uuid(C85543E5-7694-4B15-8C6B-ABB92AADA885)
	]
	coclass DistriObjsCtrl
	{
		[default] interface IDistriObjsCtrl;
	};
};

